using AwesomeAssertions;
using System.Text.Json;

namespace RoutingPatternsDemo.UnitTests;


public class StoredOpenAPIDocumentTests(HandlerTestApplicationFactory appFactory) : IClassFixture<HandlerTestApplicationFactory>
{
    /// <summary>
    /// Test for the integrity of the PR review of the build-time-generated OpenAPI document that is (or should have been) checked in to the source branch of a pull request. 
    /// </summary>
    /// <returns></returns>
    /// <remarks>
    /// <para>
    /// The OpenAPI document generated by the API should match the one generated at build time ans stored in the API project's folder as file named openapi.json. 
    /// </para>
    /// <para>
    /// If this is not the case, then in a pull request the reviewer would be looking for potential changes in an OpenAPI document that is not what the code in the source branch would generate: the checked in OpenAPI document - generated on the developer's machine during build, then check into th source branch of the PR - is stale. 
    /// </para>
    /// <para>
    /// Therefore, assuming this test would run in CI on the source branch of a pull request, it is an assert on the "integrity of the review" of the stored, build-time-generated OpenAPI document.
    /// </para>
    /// </remarks>
    [Fact]
    public async Task StoredOpenAPIDocumentSameAsThatGeneratedByAPI()
    {
        //ARRANGE
        // Locate the API project folder relative to the test assembly's location.
        // Test assembly runs from: <repoRoot>/RoutingPatternsDemo.UnitTests/bin/<Config>/<framework moniker>/
        // API project folder is:   <repoRoot>/RoutingPatternsDemo/
        var testAssemblyDir = Path.GetDirectoryName(typeof(StoredOpenAPIDocumentTests).Assembly.Location)!;
        var apiProjectDir = Path.GetFullPath(Path.Combine(testAssemblyDir, "..", "..", "..", "..", "RoutingPatternsDemo"));
        var storedOpenApiDocumentPath = Path.Combine(apiProjectDir, "openapi.json");

        // ACT
        var storedOpenApiDocumentJson = await File.ReadAllTextAsync(storedOpenApiDocumentPath);

        using var client = appFactory.CreateClient();
        var response = await client.GetAsync("/openapi/v1.json");
        response.EnsureSuccessStatusCode();
        var generatedOpenApiDocumentJson = await response.Content.ReadAsStringAsync();

        // ASSERT        
        var storedNormalised = NormalizeOpenApiDocument(storedOpenApiDocumentJson);
        var generatedNormalised = NormalizeOpenApiDocument(generatedOpenApiDocumentJson);

        generatedNormalised.Should().Be(
            storedNormalised,
            "The OpenAPI document generated by the API should match the one generated at build time and stored at {0}.",
            storedOpenApiDocumentPath);
    }

    private static string NormalizeOpenApiDocument(string json)
    {
        using var doc = JsonDocument.Parse(json);

        // Remove "servers" before comparing. At runtime, Microsoft.AspNetCore.OpenApi injects a
        // "servers" entry derived from the active host (e.g. the test client's base address).
        // The build-time generator (GetDocument.Insider) does not inject it, so without this
        // removal the two documents would always diverge on that key alone.
        var root = doc.RootElement;
        var dict = root.EnumerateObject()
            .Where(p => p.Name != "servers")
            .ToDictionary(p => p.Name, p => p.Value);

        return JsonSerializer.Serialize(dict, new JsonSerializerOptions
        {
            WriteIndented = false,
        });
    }
}
